services:

  staging_redis:
    image: redis:7-alpine
    container_name: pos_redis_staging
    ports:
      - "6380:6379"
    restart: always
    networks:
      - pos_network_staging

  staging_api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: pos_api_staging
    ports:
      - "4001:4000"
    restart: always
    depends_on:
      staging_redis:
        condition: service_started
    networks:
      - pos_network_staging
    environment:
      DATABASE_URL: postgresql://doadmin:AVNS_iNZVQYj-RX036W3B0oS@retail-craft-db-postgres-do-user-24373738-0.k.db.ondigitalocean.com:25060/pos_db_staging?sslmode=require
      APP_URL: https://staging.retailcraft.com.ng
      API_URL: https://staging.retailcraft.com.ng/api
      PORT: 4000
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/web/node_modules
      - /app/apps/api/dist
      - ./uploads_staging:/app/apps/api/uploads

  staging_web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: pos_web_staging
    ports:
      - "3001:3000"
    restart: always
    depends_on:
      staging_api:
        condition: service_started
    networks:
      - pos_network_staging
    environment:
      NEXT_PUBLIC_API_URL: https://staging.retailcraft.com.ng/api
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/api/node_modules
      - /app/apps/web/.next

networks:
  pos_network_staging:
    driver: bridge
